export const STYLE = [
    '0core',
    'Acid panda',
    'Beastie',
    'Bitcrusher',
    'Bloodsport',
    'Cadavercore',
    'Codefolk',
    'Converter',
    'Corpodrone',
    'Cosmopunk',
    'Cvlt',
    'Cybercrust',
    'CyPop',
    'Daemonista',
    'Deathbloc',
    'Doomtroop',
    'Ghoul',
    'Glitchmode',
    'Goregrinder',
    'Gutterscum',
    'Hexcore',
    'Hype street',
    'Kill mode',
    'Meta',
    'Mimic',
    'Minimal',
    'Minotaur',
    'Mobwave',
    'Monsterwave',
    'Murdercore',
    'Necropop',
    'Neurotripper',
    'NuFlesh',
    'NuGoth',
    'NuPrep',
    'Oceanwave',
    'OG',
    'Old-school cyberpunk',
    'Orbital',
    'Postlife',
    'Pyrocore',
    'Razormouth',
    'Retro metal',
    'Riot kid',
    'Robomode',
    'Roller bruiser',
    'Technoir',
    'Trad punk',
    'Wallgoth',
    'Waster',
];

export const FEATURE = [
    'Abundance of rings',
    'All monochrome body',
    'Artificial skin',
    'Beastlike body',
    'Broken nose',
    'Burn scars',
    'Completely hairless body',
    'Cosmetic gills',
    'body Covered in tattoos',
    'Customized voicebox',
    'Disheveled look',
    'Dollface',
    'Dueling scars',
    'Elaborate hairstyle',
    'Enhanced cheekbones',
    'Fluorescent veins',
    'Forehead display',
    'Giant RCD helmet rig',
    'Glitterskin',
    'Glowing respirator',
    'Golden grillz',
    'Headband',
    'heavily made up face',
    'Holomorphed face',
    'Interesting perfume',
    'Lace trimmings',
    'Laser branded body',
    'Lipless—just, teeth grimace',
    'Mirror eyes',
    'More plastic than skin body',
    'Necrotic face',
    'Nonhuman ears',
    'Palms covered in notes',
    'Pattern overdose',
    'Plenty of piercings',
    'Radiant eyebrows',
    'Rainbow haircut',
    'Ritual scarifications',
    'Robotlike body',
    'Shoulder pads',
    'Subdermal implants',
    'Tons of jewelry',
    'Traditional amulets',
    'Translucent skin',
    'Transparent wear',
    'Unkempt hair',
    'Unnatural eyes',
    'UV-inked face',
    'VIP lookalike body',
    'War paints',
];

export const WANTS = [
    'ANARCHY',
    'TO BURN IT ALL DOWN',
    'CASH',
    'DRUGS',
    'ENLIGHTENMENT',
    'FAME',
    'FREEDOM',
    'FUN',
    'JUSTICE',
    'LOVE',
    'MAYHEM',
    'POWER OVER OTHERS',
    'REVENGE',
    'SAFETY FOR LOVED ONES',
    'TO SAVE THE WORLD',
    'TO SEE OTHERS FAIL',
    'SELF-CONTROL',
    'SELF-ACTUALIZATION',
    'SUCCESS',
    'TO KILL',
];

export const QUIRK = [
    'BE A CHAINSMOKER',
    'CHEWS ON HAIR',
    'SWEAR COMPULSIVELY',
    'BE CONSTANTLY WATCHING HOLOS',
    'COUGH',
    'FIDDLE WITH JEWELRY',
    'BE FLIRTY',
    'GESTURES A LOT',
    'GIGGLE INAPPROPRIATELY',
    'WEAR HAT/HOOD AND SHADES, ALWAYS',
    'BE ITCHY',
    'LOUDLY CHEW GUM',
    'TAG EVERY LOCATION',
    'NEVER LOOKS ANYONE IN THE EYE',
    'PICK YOUR NOSE',
    'ALWAYS BE RAPIDLY BLINKING',
    'REEK OF LIGHTER FLUID',
    'SCRATCHE AT A FACIAL SCAR',
    'BE TWITCHY',
    'WHEEZE',
];

export const OBSESSION = [
    'ADRENALINE',
    'AI POETRY',
    'AMMONIUM CHLORIDE CANDY',
    'ANCIENT GRIMOIRES',
    'ARACHNIDS',
    'BELTS',
    'BLADES',
    'BONES',
    'CUSTOMIZED CARS',
    'DRONESPOTTING',
    'EXPERIMENTAL STIMULI',
    'EXPLOSIVES',
    'EXTRAVAGANT MANICURE',
    'GAUZE AND BAND-AIDS',
    'GIN',
    'GRAFFITI',
    'HAND-PRESSED SYNTHPRESSO',
    'HANDHELD GAMES',
    'HEADPHONES',
    'HISTORY SIMS',
    'INTERACTIVE HOLO-INK',
    'JOURNALING',
    'MASKS',
    'MEDIEVAL WEAPONRY',
    'MICROBOTS',
    'MIXING STIMULANTS',
    'MODEL MECH KITS',
    'OBSOLETE TECH',
    'PORCELAIN FIGURINES',
    'PRINTED SHIRTS',
    'PUPPETS',
    'RECORDS',
    'RECURSIVE SYNTHESIZERS',
    'SHADES',
    'SLACKLINING',
    'SNEAKERS',
    'STIM SMOKES',
    'STYLE HOPPING',
    'TAROT',
    'TAXIDERMY',
    'TRENDY FOOD',
    'URBAN EXPLORING',
    'VAMPIRES VS. WEREWOLVES',
    'VINTAGE ARMY JACKETS',
    'VINTAGE TV SHOWS',
    'VIRTUAFLICKS',
    'VIRTUAPALS',
    'VOICE MODULATORS',
    'WATCHES',
    'WIGS',
];